-- ⚠ CE FICHIER N'EST PLUS À JOUR ET NE DOIT PLUS ÊTRE EXÉCUTÉ. ⚠
--
-- Il contenait une policy de lecture sur `profils` en `using (true)`, sous un
-- ancien nom. Le `drop policy if exists` qui la précédait visait ce même ancien
-- nom : rejouer ce fichier sur la production AJOUTAIT donc une règle permissive
-- À CÔTÉ de la règle stricte, au lieu de la remplacer. Les policies permissives
-- se combinent en OU — la table `profils` entière, photos de visage comprises,
-- serait devenue lisible par n'importe quel compte créé sur le projet.
--
-- Il créait par ailleurs `profils` avec trois colonnes seulement, alors que le
-- client en écrit six : sur une installation neuve, l'avatar ne se synchronisait
-- jamais et l'erreur était avalée en silence.
--
-- Le schéma réel, complet et rejouable, vit maintenant dans :
--
--     /supabase/migrations/     les tables, les règles, les fonctions
--     /supabase/functions/      les trois Edge Functions
--     /supabase/INSTALL.md      l'ordre d'exécution et les vérifications
--
-- Ce fichier ne garde qu'un nom, pour que personne ne retombe sur une copie
-- périmée en cherchant « supabase » à la racine du dépôt.
