-- ⚠ CE FICHIER N'EST PLUS À JOUR ET NE DOIT PLUS ÊTRE EXÉCUTÉ. ⚠
--
-- Le schéma réel, complet et rejouable, vit maintenant dans :
--
--     /supabase/migrations/     les tables, les règles, les fonctions
--     /supabase/functions/      les trois Edge Functions
--     /supabase/INSTALL.md      l'ordre d'exécution et les vérifications
--
-- Ce fichier ne garde qu'un nom, pour que personne ne retombe sur une copie
-- périmée en cherchant « supabase » à la racine du dépôt.
